export const motivationalQuotes = [
  'La suerte es proporcional al sudor. Cuanto más sudas, más suerte tienes. - Ray Kroc',
  'Los obstáculos no tienen que frenarte. Si te encuentras con una pared, no das la vuelta y abandonas. Encuentras la manera de subir a ella, pasar a través de ella o rodearla. - Michael Jordan',
  'Asegúrate que tu peor enemigo no vive en medio de tus dos orejas. - Laird Hamilton',
  'Si tienes miedo de fallar, probablemente falles. - Kobe Bryant',
  'No se trata de si te derriban, se trata de si te levantas. - Vince Lombardi',
  'Lo que te falta de talento lo puedes contrarrestar con deseo, trabajo y dando el 110 % todo el tiempo. - Don Zimmer',
  'Si entrenas duro, no solo serás duro, serás duro de superar. - Herschel Walker',
  'Si solo das el 90 % en los entrenamientos, solo darás el 90 % cuando importe. - Michael Owen',
  '¡Nunca te rindas! El fracaso y el rechazo son sólo el primer paso para tener éxito. - Jim Valvano',
  'Un campeón es alguien que se levanta cuando el otro no puede. - William Harrison',
  'No te rindas.Sufre ahora y vive el resto de tu vida como un campeón. - Muhammad Ali',
  'Debes dar el 100 % en la primera mitad del partido.Si eso no es suficiente, en la segunda mitad debes dar todo lo que te queda.- Yogi Berra',
  'En el polvo de la derrota y en los laureles de la victoria, se puede encontrar gloria si uno dio su mejor esfuerzo. - Eric Liddell',
  'Aunque nadie puede volver atrás y hacer un nuevo comienzo, cualquiera puede comenzar a partir de ahora y crear un nuevo final. - Carl Bard',
  'Lo único que se interpone entre ti y tu sueño, es la voluntad de intentarlo y la creencia de que en realidad es posible. - Joel Brown',
  'La derrota no es el peor de los fracasos.No intentarlo es el verdadero fracaso. - George Edward Woodberry',
  'El mayor placer de la vida es hacer lo que la gente dice que no puedes hacer. - Walter Bagehot',
  'He fallado más de 9.000 tiros en mi carrera.He perdido casi 300 juegos. 26 veces, han confiado en mí para hacer un tiro ganador y he perdido.He fallado una y otra y otra vez en mi vida.Y es por eso que tenga éxito. - Michael Jordan',
  'Proponte alcanzar unas metas altas, y no te detengas hasta llegar allí. - Bo Jackson',
  'Los campeones no están hechos en el gimnasio.Los campeones están hechos de algo que tienen en su interior, un deseo, un sueño, una visión. - Muhammad Ali',
  'La adversidad hace que algunos hombres se rompan; otros rompen sus límites. - William Arthur Ward',
  'Trabaja en tu debilidad hasta que se convierta en tu fortaleza. - Knute Rockne',
  'El deporte no construye el carácter.Lo revela. - Heywood Broun',
  'El camino hacia el éxito siempre está en construcción. - Lily Tomlin'
]
